export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_SAMPLE = 'GET_SAMPLE';
export const SAMPLE_LOADING = 'SAMPLE_LOADING';
export const SAMPLE_NOT_FOUND = 'SAMPLE_NOT_FOUND';
export const CLEAR_CURRENT_SAMPLE = 'CLEAR_CURRENT_SAMPLE';
export const GET_SAMPLES = 'GET_SAMPLES';
export const DOWNLOAD_SAMPLE = 'DOWNLOAD_SAMPLE';

// WRTIEOFF TYPES
export const GET_WRITEOFF = 'GET_WRITEOFF';
export const WRITEOFF_LOADING = 'WRITEOFF_LOADING';
export const WRITEOFF_NOT_FOUND = 'WRITEOFF_NOT_FOUND';
export const CLEAR_CURRENT_WRITEOFF = 'CLEAR_CURRENT_WRITEOFF';
export const GET_WRITEOFFS = 'GET_WRITEOFFS';
export const DOWNLOAD_WRITEOFF = 'DOWNLOAD_WRITEOFF';
